### ISSUE TITLE
could only build with change in /usr/include/graphviz/types.h

### ISSUE THREAD

**Issue by cg-pasdzierny** [KDAB/KDStateMachineEditor#33] opened 2023-08-20 09:53 UTC
hello,
I am pretty sure my fix is wrong but without changing 

     line 49 #include <cgraph.h>
to 
     line 49 #include <graphviz/cgraph.h>

my build stopped with "cgraph.h not found".

I am using red hat rhel 7 with gcc 11.2.1 and graphviz-devel 2.30.1 

Thanks, Martin.

**Comment by winterz** [comment] 2023-08-20 11:46
which branch are you using?
please try master

**Comment by cg-pasdzierny** [comment] 2023-08-20 13:34
thanks for the reply.
I was using master via git.

**Comment by cg-pasdzierny** [comment] 2023-08-20 13:35
git clone https://github.com/KDAB/KDStateMachineEditor.git

**Comment by winterz** [comment] 2023-08-21 13:06
strange.
I don't see any files in the master branch that contain the line '#include <cgraph.h>'
which file do you see with that line?

**Comment by winterz** [comment] 2023-08-25 16:48
you're right.  sorry.

maybe we need to increase the minimum required graphviz version beyond 2.30.1 ?

another possibility is to pass `-DWITH_INTERNAL_GRAPHVIZ=True` to CMake, which will download and build version 2.48 for you.  no idea if that still works

and yet another possibility is to add vcpkg support

**Comment by ferdnyc** [comment] 2024-01-06 10:03
@winterz @cg-pasdzierny 

It looks to me like the `FindGraphviz.cmake` discovery code is just wrong.

As written, it will discover the include path for a `/usr/include/graphviz/cgraph.h` as `/usr/include/`:

https://github.com/KDAB/KDStateMachineEditor/blob/2567f49288575d837fe7273557fa099a814e274f/cmake/FindGraphviz.cmake#L76-L80

...But the Graphviz pkg-config data has the include path as `/usr/include/graphviz`. IOW, it expects that the `graphviz` subdirectory will be on the include path, as @cg-pasdzierny discovered:

```console
$ pkg-config --cflags libcgraph        
-I/usr/include/graphviz
```

(This is with Graphviz 8.1.0 installed on Fedora 39, but I doubt it's changed anytime recently.)

**Comment by ferdnyc** [comment] 2024-01-06 10:13
Looks to me like it should be,

```cmake
find_path( 
  GRAPHVIZ_INCLUDE_DIR 
  NAMES graph.h cgraph.h 
  HINTS ${_GRAPHVIZ_INCLUDE_DIR}
  PATH_SUFFIXES graphviz
  ${_GRAPHVIZ_FIND_OPTS} 
)
```

**Comment by iamsergio** [comment] 2024-11-15 18:02
I can't reproduce this anymore, probably fixed since then. 
Closing since we've added CI.

Reopen if still repro

**Closed by iamsergio** 2024-11-15 18:02 UTC
